### ISSUE TITLE
"Software caused connection abort"

### ISSUE THREAD

**Issue by PatrykMis** [GrapheneOS/Apps#250]
Crash occurred once after initial boot and unlock, connection check disabled in the system. Unfortunately, cannot reproduce this :( but hope it will be helpful during further development.

```
type: crash
osVersion: google/flame/flame:13/TP1A.221005.002/2022111000:user/release-keys
package: app.grapheneos.apps:7
process: app.grapheneos.apps

java.net.SocketException: Software caused connection abort
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
	at java.net.SocketInputStream.read(SocketInputStream.java:173)
	at java.net.SocketInputStream.read(SocketInputStream.java:143)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
	at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:167)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:211)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getHeaderField(DelegatingHttpsURLConnection.java:191)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getHeaderField(HttpsURLConnectionImpl.java:30)
	at o4.e.c(SourceFile:17)
	at o4.e.b(Unknown Source:41)
	at org.grapheneos.apps.client.App.b(SourceFile:1)
	at a4.t.j(Unknown Source:70)
	at y2.a.b(Unknown Source:7)
	at m3.h0.run(Unknown Source:102)
	at r3.d.run(Unknown Source:11)
	at t3.j.run(Unknown Source:2)
	at t3.a.run(SourceFile:10)
	Suppressed: m3.f0: [p1{Cancelling}@b7b169c, Dispatchers.IO]

```

**Comment by PatrykMis** [comment]
Then the software should not crash and "stop working" though but (I think) retry, throw connection error etc.

**Comment by thestinger** [comment]
The low-level implementation of Apps is currently being entirely rewritten by muhomorr. That should resolve most of the issues with it.

**Comment by thestinger** [comment]
I misunderstood what you filed and didn't realize it was actually a crash and not just a printed traceback, but it will get addressed by the rewrite.
