### ISSUE TITLE
Crash in background

### ISSUE THREAD

**Issue by opusforlife2** [GrapheneOS/Apps#270]
Scoop caught this error today. No idea when it happened, but the device was lying idle for a long time when I picked it up and noticed this crash.

Apps is at version 12.

```
FATAL EXCEPTION: main
Process: app.grapheneos.apps, PID: 18896
java.lang.ExceptionInInitializerError
	at app.grapheneos.apps.util.UtilsKt.a(Unknown Source:4)
	at app.grapheneos.apps.autoupdate.AutoUpdateJob.onStartJob(Unknown Source:12)
	at android.app.job.JobService$1.onStartJob(JobService.java:62)
	at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:105)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: j3.h: lateinit property baseAppContext has not been initialized
	at app.grapheneos.apps.core.GlobalsKt.<clinit>(Unknown Source:195)
	... 11 more
```

**Comment by thestinger** [comment]
cc @muhomorr

**Comment by muhomorr** [comment]
@opusforlife2 By "Scoop" you mean https://github.com/TacoTheDank/Scoop ?

Which device and OS version are you on?

**Comment by muhomorr** [comment]
Unable to reproduce this issue.

`baseAppContext` is unconditionally initialized in `ApplicationImpl,attachBaseContext()` which should always be the first app method that is executed by the OS when the app is being instantiated.

**Comment by muhomorr** [comment]
There's an AOSP bug that would be able to cause this issue:
https://issuetracker.google.com/issues/160946170

Do you have a an auto-backup app or service installed?

**Comment by muhomorr** [comment]
@opusforlife2 Yes
